"""initial schema with soft deletes

Revision ID: ef428d9655f7
Revises: 
Create Date: 2026-03-30 13:29:52.671408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef428d9655f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tuned_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('tuned_model_name', sa.String(), nullable=True),
    sa.Column('base_model', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('training_examples', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name')
    )
    op.create_index(op.f('ix_tuned_models_id'), 'tuned_models', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('generated_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('manufacturing_method', sa.String(), nullable=True),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('stl_path', sa.String(), nullable=True),
    sa.Column('step_path', sa.String(), nullable=True),
    sa.Column('bom_suggestion', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('generation_time_s', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_parts_id'), 'generated_parts', ['id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('upload_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    op.create_table('generation_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('prompt_snapshot', sa.Text(), nullable=True),
    sa.Column('script_snapshot', sa.Text(), nullable=True),
    sa.Column('manufacturing_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['generated_parts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_feedback_id'), 'generation_feedback', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=True),
    sa.Column('format_detail', sa.String(), nullable=True),
    sa.Column('volume_cm3', sa.Float(), nullable=True),
    sa.Column('surface_area_cm2', sa.Float(), nullable=True),
    sa.Column('volume_method', sa.String(), nullable=True),
    sa.Column('confidence_interval', sa.Float(), nullable=True),
    sa.Column('triangle_count', sa.Integer(), nullable=True),
    sa.Column('face_count', sa.Integer(), nullable=True),
    sa.Column('bbox_x_mm', sa.Float(), nullable=True),
    sa.Column('bbox_y_mm', sa.Float(), nullable=True),
    sa.Column('bbox_z_mm', sa.Float(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('is_assembly', sa.Boolean(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('bom_items', sa.JSON(), nullable=True),
    sa.Column('cogs_data', sa.JSON(), nullable=True),
    sa.Column('physics_score', sa.Integer(), nullable=True),
    sa.Column('physics_warning', sa.Text(), nullable=True),
    sa.Column('retail_price_usd', sa.Float(), nullable=True),
    sa.Column('capital_prototype', sa.Float(), nullable=True),
    sa.Column('capital_capex', sa.Float(), nullable=True),
    sa.Column('capital_total_ask', sa.Float(), nullable=True),
    sa.Column('supply_lead_time', sa.String(), nullable=True),
    sa.Column('supply_route', sa.String(), nullable=True),
    sa.Column('supply_risk', sa.String(), nullable=True),
    sa.Column('suppliers', sa.JSON(), nullable=True),
    sa.Column('optimizations', sa.JSON(), nullable=True),
    sa.Column('ai_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_generation_feedback_id'), table_name='generation_feedback')
    op.drop_table('generation_feedback')
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_generated_parts_id'), table_name='generated_parts')
    op.drop_table('generated_parts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tuned_models_id'), table_name='tuned_models')
    op.drop_table('tuned_models')
    # ### end Alembic commands ###
