"""
Layer 8 — Script Linting & Precision Overhaul

Receives the Layer 7 script (from granular_builder.py) and the GuardedPlan context,
then uses Gemini Pro to perform a multi-pass overhaul:

  1. Inject parametric constants for every magic number
  2. Add inline engineering assertions (dimension guards)
  3. Add advanced CadQuery features: polarArray, localized fillets, chamfer variants
  4. Verify tolerances, clearances, GD&T comments per feature
  5. Ensure script is 5–10× more detailed than a basic generation

After the AI overhaul, runs the existing validate_script() linter.
One retry pass if linting fails.

Location: cadfactory-backend/services/script_refiner.py
"""

from __future__ import annotations

import logging
from typing import Optional, Tuple
from dataclasses import dataclass

from services.csg_guard import GuardedPlan

logger = logging.getLogger(__name__)


# ── Output model ───────────────────────────────────────────────────────────────

@dataclass
class RefinedScript:
    success:          bool
    script:           str
    original_lines:   int = 0
    refined_lines:    int = 0
    detail_multiplier: float = 1.0
    refiner_notes:    str = ""
    error:            Optional[str] = None


# ── Layer 8 system prompt ──────────────────────────────────────────────────────

_LAYER8_REFINER_PROMPT = """
You are Layer 8 of a precision CAD pipeline: the Script Linting & Precision Overhaul agent.

You receive a working CadQuery Python script generated by a structured CSG pipeline.
Your mission: rewrite it to be 5–10× more detailed, parametric, and precision-annotated
while keeping it 100% runnable and correct.

════════════════════════════════════════════════════════════════════════════════
MANDATORY TRANSFORMATIONS:
════════════════════════════════════════════════════════════════════════════════

1. PARAMETRIC HEADER BLOCK
   Move ALL numeric literals (dimensions, radii, counts, angles) to a named
   constants block at the top of the script. Format:
   ```
   # ═══ PARAMETRIC CONSTANTS ═══════════════════════════════════════════════
   # [Layer 1-4 confidence: X.XX] [Process: FDM] [Material: ABS] [Tol: IT7]
   BODY_RADIUS_MM    = 35.0   # outer radius — Ø70mm body
   BODY_HEIGHT_MM    = 130.0  # total body height (incl. base)
   WALL_MM           = 2.5    # FDM minimum wall ≥ 1.5mm ✓
   DRAFT_RAD         = 0.026  # tan(1.5°) — injection/FDM draft taper
   SHOULDER_FILLET   = 52.5   # G2 continuity: ≥ 1.5 × body_r ✓
   NECK_RADIUS_MM    = 6.0    # solid shaft: handles τ = r×F ≥ 0.06 N·m ✓
   # ...etc
   ```

2. ENGINEERING COMMENTS PER FEATURE
   Each major primitive gets a 1-line engineering comment:
   ```
   # [main_body] V=π×35²×130=500,122mm³≈500ml shell | draft r_top=31.6mm ✓
   BODY = cq.Workplane('XY').add(cq.Solid.makeCone(BODY_R_BASE, BODY_R_TOP, BODY_H))
   # [bearing_hole] ISO 273 M6 clearance bore: Ø6.6mm ✓
   HOLE = cq.Workplane('XY').cylinder(BODY_H, HOLE_R)
   ```

3. DIMENSION GUARDS (assertions)
   Add Python assert statements before any .box() / .cylinder() call:
   ```
   assert WALL_MM >= 1.5, f"FDM wall {WALL_MM}mm below minimum 1.5mm"
   assert BODY_H > 0 and BODY_R_BASE > 0, "body dims must be positive"
   ```

4. LOCALIZED FILLETS
   Replace any global `.edges().fillet(r)` with targeted selectors:
   ```
   try: result = result.edges("|Z").fillet(BODY_FILLET)
   except Exception: pass
   try: result = result.faces(">Z").edges().chamfer(0.5)  # top lip chamfer
   except Exception: pass
   ```

5. ADVANCED FEATURES (use where applicable):
   - `.polarArray(radius, startAngle, angle, count)` for circular patterns
   - `cq.Solid.makeCone(r_base, r_top, h)` for drafted cylinders (not bare cylinder)
   - `.cboreHole(hole_d, cbore_d, cbore_depth)` for counterbore fastener holes
   - `.cskHole(hole_d, csk_d, csk_angle)` for countersunk screw holes
   - `cq.Solid.makeSphere(r, center)` for rounded tip caps
   - Named workplane labels: `.tag("top_face")` before selectors

6. GD&T TOLERANCE COMMENTS
   For every hole:
   ```
   # Hole: M4 clearance ISO 273 fine = 4.5mm dia | IT7 = ±0.012mm @Ø4.5
   ```

7. MATERIAL & PHYSICS NOTES (in header block):
   ```
   # Material: ABS | E=2200MPa | ρ=1.05g/cm³ | yield σ=40MPa
   # Barlow: t_min = P·r/σ = 0.2MPa×35/(40/3) = 0.52mm → using 2.5mm (SF=4.8) ✓
   # Euler: h/t = 130/2.5 = 52 > 20 → body needs draft (applied via cone) ✓
   ```

   8. STRUCTURAL INTEGRITY (GAP ELIMINATION)
   Check every `.pos()` / `.translate()` for stacked parts.
   If Part B sits on Part A, their Z-positions MUST result in a 2mm overlap.
   Formula: pos_z = (h_bottom/2) + (h_top/2) - 2.0.
   NEVER leave a gap between unioned solids.

════════════════════════════════════════════════════════════════════════════════
HARD RULES (you MUST follow):
════════════════════════════════════════════════════════════════════════════════
- Script must be fully runnable. No syntax errors. No undefined variables.
- All magic numbers from the original MUST be moved to the constants block.
- Do NOT invent new geometry not in the original script.
- Do NOT remove any existing shapes or operations.
- Keep `result` as final variable. `show_object(result)` as last line.
- Only `import cadquery as cq` (plus `import math` if needed).
- Wrap every fillet in try/except.
- Use `.faces(">Z")` style selectors — never `edges(">Z")`.
- Output ONLY Python code — no markdown, no backticks, no explanation.
- The output script MUST have MORE lines than the input. Aim for 3–8× minimum.
"""


# ── Core function ──────────────────────────────────────────────────────────────

async def refine_script_layer8(
    script: str,
    guarded_plan: Optional[GuardedPlan] = None,
    object_name: str = "",
    manufacturing_process: str = "fdm",
    material: str = "ABS",
    tolerance_class: str = "IT7",
    layer14_confidence: float = 0.8,
) -> RefinedScript:
    """
    Layer 8: Run the AI precision overhaul on a Layer 7 CadQuery script.

    Returns RefinedScript with the densified, fully parametric script.
    Falls back to returning the original script if AI overhaul fails.
    """
    from services.claude_cad import _generate_content, MODEL_PRO
    from services.script_utils import extract_python_code, validate_script

    original_lines = script.count("\n") + 1

    # Build context preamble for the AI
    context_hints = [
        f"# Object: {object_name or 'Part'}",
        f"# Manufacturing: {manufacturing_process.upper()}",
        f"# Material: {material} | Tolerance class: {tolerance_class}",
        f"# Layer 1-4 pipeline confidence: {layer14_confidence:.2f}",
    ]
    if guarded_plan:
        context_hints.append(
            f"# Guard warnings: {len(guarded_plan.risk_flags)} | "
            f"AI notes: {'; '.join(guarded_plan.ai_notes[:2])}"
        )

    user_msg = "\n".join(context_hints) + "\n\n# ─── INPUT SCRIPT ───\n" + script

    # ── First attempt ────────────────────────────────────────────────────────
    refined_script = None
    for attempt in range(2):
        try:
            raw = _generate_content(MODEL_PRO, _LAYER8_REFINER_PROMPT, user_msg)
            candidate = extract_python_code(raw)
            if not candidate:
                logger.warning(f"Layer 8 attempt {attempt+1}: no Python code extracted")
                continue

            is_valid, lint_warnings = validate_script(candidate)
            if is_valid:
                refined_script = candidate
                logger.info(f"Layer 8: script accepted on attempt {attempt+1}, "
                            f"{candidate.count(chr(10))+1} lines")
                break
            else:
                logger.warning(
                    f"Layer 8 attempt {attempt+1} failed lint: {lint_warnings[:2]}"
                )
                # Feed lint errors back into second attempt
                user_msg = (
                    f"The previous refactored script failed validation:\n"
                    f"{chr(10).join(lint_warnings[:5])}\n\n"
                    f"Fix these issues and re-apply all transformations.\n\n"
                    f"Original script:\n{script}"
                )
        except Exception as exc:
            logger.error(f"Layer 8 attempt {attempt+1} API error: {exc}")

    if not refined_script:
        logger.warning("Layer 8: all attempts failed — returning original script unchanged")
        return RefinedScript(
            success=False,
            script=script,
            original_lines=original_lines,
            refined_lines=original_lines,
            detail_multiplier=1.0,
            error="Layer 8 refiner failed — using original Layer 7 script",
        )

    refined_lines = refined_script.count("\n") + 1
    multiplier = refined_lines / max(original_lines, 1)

    return RefinedScript(
        success=True,
        script=refined_script,
        original_lines=original_lines,
        refined_lines=refined_lines,
        detail_multiplier=round(multiplier, 2),
        refiner_notes=f"Script expanded {multiplier:.1f}× ({original_lines}→{refined_lines} lines)",
    )
